/* tslint:disable */
/* eslint-disable */
/**
 * Todo api
 * ### Introduction   Endpoints specifications and data structures for Todo API\\ 
 *
 * The version of the OpenAPI document: 0.0.3
 * Contact: franco1conci@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

